config/routes.rb
Rails.application.routes.draw do
  get 'institucionals/about'

  get 'institucionals/terms'

  get 'institucionals/contact'

  scope module: 'admin' do
    resources :brands
    resources :stores
    resources :products
    resources :deals
    resources :articles do
      resources :pictures
    end
    resources :newsletter_users, only: :create
    get "/category", to: "articles#category"
    get 'tags/:tag', to: 'articles#category', as: :tag
    root to: "articles#index"
  end

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

end

app/models/admin/article.rb
module Admin
  class Article < ActiveRecord::Base
    acts_as_taggable
    has_many :comments, as: :commentable
    has_many :deals
    has_many :pictures    
    accepts_nested_attributes_for :deals

    # to search the last 4 top_articles from a specific category
    def self.top_articles category_name
      category = Admin::Category.find_by(name: category_name)
      deals = category.deals.limit(4).includes(:article).where(articles: {top_deal: false}) if category
      articles = []
      deals.map do |deal|
        articles << deal.article if deal.article
      end
      articles
    end


    # to search the last 4 old_top_articles from a specific category
    # def self.old_top_articles category_name
    #   i = [1,2,3,4]
    #   top_articles = self.top_articles category_name
    #   n = top_articles.first.id
    #   p = i.map {|number| n+ number }
    #   Admin::Article.where("id IN (?)", p)
    # end

    def category_name
      deal = Admin::Deal.find_by(article_id: id)
      category_name = deal.category_name
    end

    def sub_category_name
      deal = Admin::Deal.find_by(article_id: id)
      sub_category_name = deal.sub_category_name
    end

    def category_count
      category = Admin::Category.find_by(name: category_name)
      category_id= category.id
      deals = Admin::Deal.where(category_id: category_id).count
    end

    def category_articles
      category = Admin::Category.find_by(name: category_name)
      deals = category.deals.includes(:article)
      articles = []
      deals.map do |deal|
        articles << deal.article
      end
      articles
    end

    def previous_article
      article_id = id - 1
      Admin::Article.find_by(id: article_id)
    end

    def next_article
      article_id = id + 1
      Admin::Article.find_by(id: article_id)
    end

  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController

  def index
    @articles = Admin::Article.all.limit(15)
    # if query[:params]
    # end
  end

  def new
    @article = Admin::Article.new
    @deal = @article.deals.new
  end

  def create
    if @article = Admin::Article.create(article_params)
      redirect_to article_pictures_path(article_id: @article.id)
    end
  end

  def show
    @article = Admin::Article.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def category
    if params[:tag]
      @articles = Admin::Article.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 6)
    elsif  params[:query]
      @articles = Admin::Article.where("title ilike :q or content ilike :q", q: "%#{params[:query]}%").includes(:pictures).paginate(page: params[:page], per_page: 6)
    else
      @articles = Admin::Article.all.paginate(page: params[:page], per_page: 6)
    end
  end


  private

    def article_params
      params.require(:admin_article).permit( :title, :content, :tag_list, deals_attributes: [:brand_name, :product_description, :category_name, :sub_category_name, :store_name] )
    end

end

app/helpers/admin/articles/articles_helper.rb
module Admin::Articles::ArticlesHelper

	def slide_show article 
		article.pictures.count > 1
	end
end

app/views/admin/articles/_article.html.erb
<!-- Main Body -->
<div class="container">
   <!-- Main Left side -->
   <div class="main-left-side">
      <!-- The Article -->
      <div class="artcl-main float-width">
         
         <div class="artcl-body float-width">
            <h2><%= @article.title %></h2>
            <h5>
               <span><i class="fa fa-user"></i><%= @article.author %></span>
               <span><i class="fa fa-clock-o"></i><%= @article.created_at.strftime("%d/%m/%y - %H:%M") %></span>
               <span><i class="fa fa-comment-o"></i><%= @article.comments.count %></span>
            </h5>
            <% if slide_show @article%>
               <p>
                  <%= link_to article_picture_path(article_id: params[:id], picture_id: @article.pictures[1].id), method: :get, class: "btn btn-success" do %>
                     <%= "Ver imagens" %>
                  <% end %>
               </p>
            <% end %>              
            <article class="float-width articl-data">
            <%= image_tag(@article.pictures.first.image_url(:post_image), alt: "Blog") %>
               <p>
                  <%= @article.content.html_safe %>
               </p>
            </br>
            </br>
               <% if slide_show @article%>
                  <p>
                     <%= link_to article_picture_path(article_id: params[:id], picture_id: @article.pictures[1].id), method: :get, class: "btn btn-success" do %>
                        <%= "Ver imagens" %>
                     <% end %>
                  </p>
               <% end %>                  
            </article>
         </div>
      </div>
      <!-- The Article Social Media Share -->
      <div class="artcl-scl float-width">
         <div class="lefty artcl-tags">
            <h3>Tags: <%= raw @article.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %> </h3>

         </div>
         <div class="righty artcl-shr">
            <ul>
               <li>
                  <a href="https://twitter.com/share" class="twitter-share-button">Tweet</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
               </li>
               <li>
                  <div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count"></div>
               </li>
               <li>
                  <a href="whatsapp://send" data-text="Take a look at this awesome website:" data-href="" class="wa_btn wa_btn_s" style="display:none">Share</a>
               </li>
            </ul>
         </div>
      </div>
      <!-- Article Comments Section -->
       <!-- render "comments" %> -->
      <!-- related Articles  -->
      <div class="artcl-reltd float-width">
         <h3 class="sec-title">POSTS RELACIONADOS</h3>
         <% @article.category_articles.last(4).each do |article| %>
         <div class="reltd-sngl">
            <%= image_tag(article.pictures.first.image_url(:small), alt: "Blog") %>
            <div class="reltd-sngl-txt">
               <h3><%= article.title %> </h3>
               <p><i class="fa fa-clock-o"></i><%= article.created_at.strftime("%d/%m/%y - %H:%M") %></p>
            </div>
         </div>
         <% end %>
      </div>
   </div>
</div>

app/views/admin/articles/_category_news.html.erb
<div class="container">
   <!-- Main Left side -->
   <div class="main-left-side">
      <!-- Single Category News Blocks -->
      <div class="news-sec-1 float-width">
         <div class="float-width sec-cont2">
            <h3 class="sec-title">MUSIC NEWS</h3>
            <% @articles.each do | article| %>
            <div class="sec-1-big float-width">
            <%= image_tag(article.image_url(:index_mid_2), alt: "Blog", class: "blocky" ) %>
               <div class="sec-1-big-text lefty">
                  <h3><%= article.title %></h3>
                  <h6><span><i class="fa fa-user"></i>John Doe</span><span><i class="fa fa-clock-o"></i>20 Jan 2014</span><span><i class="fa fa-comment-o"></i>21 comments</span></h6>
                  <p><%= article.content %></p>
               </div>
            </div>
            <% end %>
         </div>
         <div class="cat-pagintn float-width">
            <ul>
               <li><a class="crnt-pg">1</a></li>
               <li><a href="#">2</a></li>
               <li><a href="#">3</a></li>
               <li><a href="#">4</a></li>
               <li><a href="#">5</a></li>
               <li><a href="#">6</a></li>
               <li><a href="#">7</a></li>
               <li><a href="#">...</a></li>
               <li><a href="#">22</a></li>
            </ul>
         </div>
         <div class="cat-pagintn float-width" >
         <%= will_paginate @articles, previous_label: h("<"), next_label: h(">") %>
         </div>
      </div>
   </div>
</div>

app/views/admin/articles/_deal_fields.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>jQuery UI Autocomplete - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script>
  $(function() {
    $( "#brand_name_auto_complete" ).autocomplete({
      source: $('#brand_name_auto_complete').data('autocomplete-source')
    });
    $( "#store_name_auto_complete" ).autocomplete({
      source: $('#store_name_auto_complete').data('autocomplete-source')
    });
    $( "#product_description_auto_complete" ).autocomplete({
      source: $('#product_description_auto_complete').data('autocomplete-source')
    });
  });
  </script>
</head>
<body>

<div class="field">

   <%= f.label :product_description %>
   <%= f.text_field :product_description, id: "product_description_auto_complete", data: {autocomplete_source: products_path}, class:"form-control"  %><br/><br/>

   <%= f.label :brand_name %>
   <%= f.text_field :brand_name, id: "brand_name_auto_complete", data: {autocomplete_source: brands_path}, class:"form-control"  %><br/><br/>

   <%= f.label :store_name %>
   <%= f.text_field :store_name, id: "store_name_auto_complete", data: {autocomplete_source: stores_path}, class:"form-control"  %><br/><br/>


   <%= f.label :category_name %>
   <%= f.collection_select :category_name, Admin::Category.all,:name,:name, include_blank: true  %><br /><br/>

   <%= f.label :sub_category_name %>
   <%= f.collection_select :sub_category_name, Admin::SubCategory.all,:name,:name, include_blank: true  %><br /><br/>


 </div>


</body>
</html>

app/views/admin/articles/_images_sliders.html.erb
<div class="sm-gal-cont float-width">
   <h3 class="sec-title">TOURISM - GALLERY</h3>
   <div class="sm-gal-bg">
      <a href="#"><img alt="" src="img/samples/z5.jpg" /></a>
   </div>
   <div class="flexslider img-sm-gal righty">
      <ul class="slides">
         <li>
            <img alt="" src="img/samples/r1.jpg" />
            <img alt="" src="img/samples/r5.jpg" />
         </li>
         <li>
            <img alt="" src="img/samples/r2.jpg" />
            <img alt="" src="img/samples/r6.jpg" />
         </li>
         <li>
            <img alt="" src="img/samples/r3.jpg" />
            <img alt="" src="img/samples/r7.jpg" />
         </li>
         <li>
            <img alt="" src="img/samples/r4.jpg" />
            <img alt="" src="img/samples/r8.jpg" />
         </li>
         <li>
            <img alt="" src="img/samples/r1.jpg" />
            <img alt="" src="img/samples/r5.jpg" />
         </li>
         <li>
            <img alt="" src="img/samples/r2.jpg" />
            <img alt="" src="img/samples/r6.jpg" />
         </li>
         <li>
            <img alt="" src="img/samples/r3.jpg" />
            <img alt="" src="img/samples/r7.jpg" />
         </li>
         <li>
            <img alt="" src="img/samples/r4.jpg" />
            <img alt="" src="img/samples/r8.jpg">
         </li>
         <li>
            <img alt="" src="img/samples/r1.jpg" />
            <img alt="" src="img/samples/r5.jpg" />
         </li>
         <li>
            <img alt="" src="img/samples/r2.jpg" />
            <img alt="" src="img/samples/r6.jpg" />
         </li>
         <li>
            <img alt="" src="img/samples/r3.jpg" />
            <img alt="" src="img/samples/r7.jpg">
         </li>
         <li>
            <img alt="" src="img/samples/r4.jpg" />
            <img alt="" src="img/samples/r8.jpg" />
         </li>
         <li>
            <img alt="" src="img/samples/r1.jpg" />
            <img alt="" src="img/samples/r5.jpg" />
         </li>
         <li>
            <img alt="" src="img/samples/r2.jpg" />
            <img alt="" src="img/samples/r6.jpg" />
         </li>
         <li>
            <img alt="" src="img/samples/r3.jpg" />
            <img alt="" src="img/samples/r7.jpg" />
         </li>
         <li>
            <img alt="" src="img/samples/r4.jpg" />
            <img alt="" src="img/samples/r8.jpg" />
         </li>
      </ul>
   </div>
</div>

app/views/admin/articles/_main_menu.html.erb
<div class="main-menu">
   <div class="container">
      <div class="row">
         <div class="col-lg-8">
            <!-- Main Menu -->
            <ul id="main-menu-items" class="sm sm-menu menu-efct">
               <% Admin::Category.all.each do |category| %>
               <li class="mega-menu-li">
                  <a href="#"><%= category.name %></a>
                  <!-- Main Menu - Mega Menu -->
                  <ul class="mega-menu sub-1st">
                  <% Admin::Article.top_articles(category.name).each do |article| %>
                     <li>
                        <div class="sec-1-sm">
                           <%= image_tag(article.image_url(:small), alt: "Blog", class: "lefty" ) %>
                           <div class="sec-1-sm-text blocky">
                              <h3><%=article.title %></h3>
                              <h6><span><i class="fa fa-clock-o"></i><%=article.created_at %></span><span><i class="fa fa-comment-o"></i>21 comments</span></h6>
                              <p class= "giveMeEllipsis_2"><%=article.content %></p>
                           </div>
                        </div>
                     </li>
                     <% end %>
                  </ul>
               </li>
               <% end %>
            </ul>
         </div>
         <div class="col-lg-4 main-search-bar">
            <!-- Top Search bar -->
            <%= form_tag category_path, method: :get , class:"navbar-form float-width", role:"search" do %>
               <div class="form-group float-width">
                  <%= text_field_tag :query, params[:query], type:"text", class:"form-control float-width", placeholder:"Procure uma oferta" %>
               </div>
               <a href="#" type="submit"><i class="fa fa-search"></i></a>
            <% end %>
            </div>
      </div>
      <!-- Close the Fixed Menu button -->
      <a class="fxd-mnu-x trans1" title="Close" id="hidemenu"><span class="fa-stack fa-lg"> <i class="fa fa-times fa-stack-1x fa-inverse"></i> </span></a>
   </div>
</div>

app/views/admin/articles/_music_news.html.erb
<div class="news-sec-1 float-width">
   <div class="float-width sec-cont2">
      <h3 class="sec-title">MUSIC NEWS</h3>
      <div class="sec-1-big float-width">
         <%= image_tag(@articles[6].pictures.first.image_url(:small), alt: "Blog", class: "lefty" ) %>
         <div class="sec-1-big-text lefty">
            <h3 class= "giveMeEllipsis_2"><%= link_to @articles[6].title, article_path(id: @articles[6].id), method: :get %></h3>
            <h6><span><i class="fa fa-user"></i>Daniele Pedroso</span><span><i class="fa fa-clock-o"></i><%= @articles[6].created_at.strftime("%d/%m/%y - %H:%M") %></span><span><i class="fa fa-comment-o"></i>21 comments</span></h6>
            <%= link_to(article_path(id: @articles[6].id), method: :get) do %>
            <p class= "giveMeEllipsis_6"><%= @articles[6].content.html_safe %></p>
            <% end %>
         </div>
      </div>
      <div class="sec-1-sm">
      <%= image_tag(@articles[7].pictures.first.image_url(:small), alt: "Blog", class: "lefty" ) %>
         <div class="sec-1-sm-text blocky">
            <h3 class= "giveMeEllipsis_2"><%= link_to @articles[7].title, article_path(id: @articles[7].id), method: :get %></h3>
            <h6><span><i class="fa fa-clock-o"></i><%= @articles[7].created_at.strftime("%d/%m/%y - %H:%M") %></span><span><i class="fa fa-comment-o"></i>21 comments</span></h6>
            <%= link_to(article_path(id: @articles[7].id), method: :get) do %>
            <p class= "giveMeEllipsis_2"><%= @articles[7].content.html_safe %></p>
            <% end %>
         </div>
      </div>
      <div class="sec-1-sm">
      <%= image_tag(@articles[8].pictures.first.image_url(:small), alt: "Blog", class: "lefty" ) %>
         <div class="sec-1-sm-text blocky">
            <h3 class= "giveMeEllipsis_2"><%= link_to @articles[8].title, article_path(id: @articles[8].id), method: :get %></h3>
            <h6><span><i class="fa fa-clock-o"></i><%= @articles[8].created_at.strftime("%d/%m/%y - %H:%M") %></span><span><i class="fa fa-comment-o"></i>21 comments</span></h6>
            <p class= "giveMeEllipsis_2"><%= @articles[8].content.html_safe %></p>
         </div>
      </div>
      <div class="sec-1-sm">
      <%= image_tag(@articles[9].pictures.first.image_url(:small), alt: "Blog", class: "lefty" ) %>
         <div class="sec-1-sm-text blocky">
            <h3 class= "giveMeEllipsis_2"><%= link_to @articles[9].title, article_path(id: @articles[9].id), method: :get %></h3>
            <h6><span><i class="fa fa-clock-o"></i><%= @articles[9].created_at.strftime("%d/%m/%y - %H:%M") %></span><span><i class="fa fa-comment-o"></i>21 comments</span></h6>
            <%= link_to(article_path(id: @articles[9].id), method: :get) do %>
            <p class= "giveMeEllipsis_2"><%= @articles[9].content.html_safe %></p>
            <% end %>
         </div>
      </div>
      <div class="sec-1-sm">
      <%= image_tag(@articles[10].pictures.first.image_url(:small), alt: "Blog", class: "lefty" ) %>
         <div class="sec-1-sm-text blocky">
            <h3 class= "giveMeEllipsis_2"><%= link_to @articles[10].title, article_path(id: @articles[10].id), method: :get %></h3>
            <h6><span><i class="fa fa-clock-o"></i><%= @articles[10].created_at.strftime("%d/%m/%y - %H:%M") %></span><span><i class="fa fa-comment-o"></i>21 comments</span></h6>
            <%= link_to(article_path(id: @articles[10].id), method: :get) do %>
            <p class= "giveMeEllipsis_2"><%= @articles[10].content.html_safe %></p>
            <% end %>
         </div>
      </div>
   </div>
</div>

app/views/admin/articles/_slide.html.erb
<div class="qk-slider float-width">
   <h3 class="sldr-title">slider</h3>
   <div class="flexslider news-sldr">
      <ul class="slides">
         <% @articles.each do |article| %>
            <li>
               <div class="trans2 slide-sngl">
                  <a class="text-center" href="#"><%= image_tag(article.pictures.first.image_url(:small_2), alt: "Blog", class: "lefty" ) %></a>
                  <h4><a href="#"><%= link_to article.title, article_path(id: article.id), method: :get %></a></h4>
                  <%= link_to(article_path(id: article.id), method: :get) do %>
                  <p class= "giveMeEllipsis_3"><%= article.content.html_safe %></p>
                  <% end %>
                  <h6><span><i class="fa fa-clock-o"></i><%= article.created_at.strftime("%d/%m/%y - %H:%M") %></span></h6>
               </div>
            </li>
         <% end %>
      </ul>
   </div>
</div>

app/views/admin/articles/_top_deals.html.erb
<div class="container">
   <div class="main-news-blks">
      <div class="hm-slider-cont">
         <!-- News slider -->
         <div class="flex-container">
            <div class="flexslider hm-slider">
               <ul class="slides">
                  <% Admin::Article.top_articles("saúde").each do |article| %>
                     <li>
                        <%= image_tag article.pictures.first.image_url(:index_top_left) if article %>
                        <h3 class="cat-label cat-label1"><a href="#"><%= article.category_name %></a></h3>
                        <div class="hm-sldr-caption">
                           <h3 class= "giveMeEllipsis_2"><a href="#"><%=link_to article.title, article_path(id: article.id), method: :get %><span ><%= article.category_count %></span></a></h3>
                           <p class= "giveMeEllipsis_3">
                              <%= article.content.html_safe %>
                           </p>
                        </div>
                     </li>
                  <% end %>
               </ul>
            </div>
         </div>
      </div>
      <!-- Fixed Blocks -->
      <div class="mid-blks-cont">
         <!-- Block1 -->
         <div class="mid-block-1 boxgrid caption">
            <%= image_tag Admin::Article.top_articles("saúde")[0].pictures.first.image_url(:index_top_left) if Admin::Article.top_articles("saúde") %>
            <h4 class="cat-label cat-label2"><a href="#"><%=Admin::Article.top_articles("saúde")[0].category_name %></a></h4>
            <div class="cover boxcaption">
               <h3><a href="#single.html"><%= Admin::Article.top_articles("saúde")[0].title %></a><span ><%= Admin::Article.top_articles("saúde")[0].category_count %></span></h3>
               <p class= "giveMeEllipsis_2">
                  <%= Admin::Article.top_articles("saúde")[0].content.html_safe %>
               </p>
               <%= link_to(article_path(id: Admin::Article.top_articles("saúde")[0].id), method: :get) do %>
               Mais <i class="fa fa-angle-double-right">
               </i>
               <% end %>
            </div>
         </div>
         <!-- Block2 -->
         <div class="mid-block-2 boxgrid caption">
            <%= image_tag Admin::Article.top_articles("saúde")[1].pictures.first.image_url(:index_top_left) if Admin::Article.top_articles("saúde") %>
            <h4 class="cat-label cat-label3"><a href="#"><%=Admin::Article.top_articles("saúde")[1].category_name %></a></h4>
            <div class="cover boxcaption">
               <h3><a href="#single.html"><%= Admin::Article.top_articles("saúde")[1].title %></a><span><%= Admin::Article.top_articles("saúde")[1].category_count %></span></h3>
               <p class= "giveMeEllipsis_2">
                  <%= Admin::Article.top_articles("saúde")[1].content.html_safe %>
               </p>
               <%= link_to(article_path(id: Admin::Article.top_articles("saúde")[1].id), method: :get) do %>
               Mais <i class="fa fa-angle-double-right">
               </i>
               <% end %>
            </div>
         </div>
      </div>
      <!-- Block3 -->
      <div class="rt-bk-cont">
         <div class="rt-block boxgrid2 caption">
            <%= image_tag Admin::Article.top_articles("saúde")[2].pictures.first.image_url(:index_top_left) if Admin::Article.top_articles("saúde") %>
            <h4 class="cat-label cat-label4"><a href="#"><%=Admin::Article.top_articles("saúde")[2].category_name %></a></h4>
            <div class="cover boxcaption">
               <h3><a href="#single.html"><%= Admin::Article.top_articles("saúde")[2].title %></a><span ><%= Admin::Article.top_articles("saúde")[2].category_count %></span></h3>
               <p class= "giveMeEllipsis_2">
                  <%= Admin::Article.top_articles("saúde")[2].content.html_safe %>
               </p>
               <%= link_to(article_path(id: Admin::Article.top_articles("saúde")[2].id), method: :get) do %>
               Mais <i class="fa fa-angle-double-right">
               </i>
               <% end %>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/admin/articles/_top_news.html.erb
<div class="top-news float-width">
   <div class="float-width sec-cont">
      <h3 class="sec-title">Top news</h3>
      <div class="top-big-two">
         <div class="big-two-1 blocky boxgrid3 caption">
            <%= image_tag @articles[0].pictures.first.image_url(:index_mid, class: "lefty")%>
            <div class="cover boxcaption3">
               <h3><a href="#single.html"><%= link_to @articles[0].title, article_path(id: @articles[0].id), method: :get %></a></h3>
               <p class="artcl-time-1">
                  <span><i class="fa fa-clock-o"></i><%= @articles[0].created_at.strftime("%d/%m/%y - %H:%M") %></span>
                  <span><i class="fa fa-comment-o"></i>21 comments</span>
                  <%= link_to(article_path(id: @articles[0].id), method: :get) do %>
                  <span><i class="fa fa-comment-o"></i>Ver</span>
                  </i>
                  <% end %>
               </p>
               <p class= "giveMeEllipsis_2"><%= @articles[0].content.html_safe %></p>
            </div>
         </div>
         <div class="big-two-2 blocky boxgrid3 caption">
            <%= image_tag @articles[1].pictures.first.image_url(:index_mid, class: "lefty")%>
            <div class="cover boxcaption3">
               <h3><a href="#single.html"><%= link_to @articles[1].title, article_path(id: @articles[1].id), method: :get %></a></h3>
               <p class="artcl-time-1">
                  <span><i class="fa fa-clock-o"></i><%= @articles[1].created_at.strftime("%d/%m/%y - %H:%M") %></span>
                  <span><i class="fa fa-comment-o"></i>21 comments</span>
                  <%= link_to(article_path(id: @articles[1].id), method: :get) do %>
                  <span><i class="fa fa-comment-o"></i>Ver</span>
                  </i>
                  <% end %>
               </p>
               <p class= "giveMeEllipsis_2"><%= @articles[1].content.html_safe %></p>
            </div>
         </div>

      </div>
   </div>
   <div class="tn-small-1 blocky">
      <a href="#"><%= image_tag(@articles[2].pictures.first.image_url(:small), alt: "Blog", class: "lefty" ) %></a>
      <h4 class="lefty giveMeEllipsis_2"><%= link_to @articles[2].title, article_path(id: @articles[2].id), method: :get %></h4></br></br>
      <a class="lefty cat-a cat-label4" href="#"><%= @articles[2].category_name %></a></br>
      <p class="righty"><span><i class="fa fa-clock-o"></i><%= @articles[2].created_at.strftime("%d/%m/%y - %H:%M") %></span></p>
   </div>
   <div class="tn-small-1 blocky">
      <a href="#"><%= image_tag(@articles[3].pictures.first.image_url(:small), alt: "Blog", class: "lefty" ) %></a>
      <h4 class="lefty giveMeEllipsis_2"><%= link_to @articles[3].title, article_path(id: @articles[3].id), method: :get %></h4></br></br>
      <a class="lefty cat-a cat-label2" href="#"><%= @articles[3].category_name %></a></br>
      <p class="righty"><span><i class="fa fa-clock-o"></i><%= @articles[3].created_at.strftime("%d/%m/%y - %H:%M") %></span></p>
   </div>
   <div class="tn-small-1 blocky">
      <a href="#"><%= image_tag(@articles[4].pictures.first.image_url(:small), alt: "Blog", class: "lefty" ) %></a>
      <h4 class="lefty giveMeEllipsis_2"><%= link_to @articles[4].title, article_path(id: @articles[4].id), method: :get %></h4></br></br>
      <a class="lefty cat-a cat-label3" href="#"><%= @articles[4].category_name %></a></br>
      <p class="righty"><span><i class="fa fa-clock-o"></i><%= @articles[4].created_at.strftime("%d/%m/%y - %H:%M") %></span></p>
   </div>
   <div class="tn-small-1 blocky">
      <a href="#"><%= image_tag(@articles[5].pictures.first.image_url(:small), alt: "Blog", class: "lefty" ) %></a>
      <h4 class="lefty giveMeEllipsis_2"><%= link_to @articles[5].title, article_path(id: @articles[5].id), method: :get %></h4></br></br>
      <a class="lefty cat-a cat-label5" href="#"><%= @articles[5].category_name %></a></br>
      <p class="righty"><span><i class="fa fa-clock-o"></i><%= @articles[5].created_at.strftime("%d/%m/%y - %H:%M") %></span></p>
   </div>
</div>